#!/bin/bash

echo "🧪 Testing MacWhisper Global Hotkeys"
echo "====================================="
echo ""
echo "This script will help you test if global hotkeys are working properly."
echo ""
echo "1. 📱 First, run MacWhisper:"
echo "   ./run.sh"
echo ""
echo "2. 🔍 Check the console output for:"
echo "   ✅ 'Global hotkey registered successfully!'"
echo "   ✅ 'All permissions granted - global hotkeys should work!'"
echo ""
echo "3. 🎯 If you see errors:"
echo "   ❌ 'Missing accessibility permission' → Grant accessibility permission"
echo "   ❌ 'Failed to register hotkey' → Check for conflicting shortcuts"
echo ""
echo "4. 🧪 Test the hotkey:"
echo "   • Open any text app (TextEdit, Notes, etc.)"
echo "   • Press and hold Control + Space"
echo "   • The menu bar icon should turn red 🔴"
echo "   • Say something like 'Hello, this is a test'"
echo "   • Release Control + Space"
echo "   • The text should appear automatically"
echo ""
echo "5. 🔧 If it's not working:"
echo "   • Make sure MacWhisper is in System Preferences → Security & Privacy → Accessibility"
echo "   • Restart MacWhisper after granting permissions"
echo "   • Check Console.app for 'MacWhisper' logs"
echo ""
echo "6. 📊 Common issues:"
echo "   • Spotlight using Control + Space → Change Spotlight shortcut in System Preferences"
echo "   • Other apps using Control + Space → Check for conflicts"
echo "   • Missing permissions → Grant accessibility and microphone access"
echo ""
echo "Ready to test? Press Enter to continue..."
read

echo "🚀 Starting MacWhisper with debug output..."
echo ""
./MacWhisper.app/Contents/MacOS/MacWhisper 